// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlqaVCSP9W6Nt06q9n2nyMrOAT2MPiFXc',
    appId: '1:284096227824:web:f1a8261ce9af4672461535',
    messagingSenderId: '284096227824',
    projectId: 'testcodes-96c39',
    authDomain: 'testcodes-96c39.firebaseapp.com',
    storageBucket: 'testcodes-96c39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADMYU81cGRFuVSNddeZDLk9D8IfXfJeMU',
    appId: '1:284096227824:android:36349783e36a1a6a461535',
    messagingSenderId: '284096227824',
    projectId: 'testcodes-96c39',
    storageBucket: 'testcodes-96c39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtOHFmOJ52EOGXceOFWRE4zQbOzSAgP5U',
    appId: '1:284096227824:ios:42ba825bb7603964461535',
    messagingSenderId: '284096227824',
    projectId: 'testcodes-96c39',
    storageBucket: 'testcodes-96c39.appspot.com',
    iosBundleId: 'com.example.trainingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtOHFmOJ52EOGXceOFWRE4zQbOzSAgP5U',
    appId: '1:284096227824:ios:42ba825bb7603964461535',
    messagingSenderId: '284096227824',
    projectId: 'testcodes-96c39',
    storageBucket: 'testcodes-96c39.appspot.com',
    iosBundleId: 'com.example.trainingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlqaVCSP9W6Nt06q9n2nyMrOAT2MPiFXc',
    appId: '1:284096227824:web:d2b013801cbebb86461535',
    messagingSenderId: '284096227824',
    projectId: 'testcodes-96c39',
    authDomain: 'testcodes-96c39.firebaseapp.com',
    storageBucket: 'testcodes-96c39.appspot.com',
  );
}
